//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_ActualizarEstudiante_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_ActualizarEstudiante_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\Alessander\AppData\Local\Temp\0952D34EF67DECA0378A41CAA6B9A7664B7A\4\Arquimedes\Arquimedes\Views\Estudiante\ActualizarEstudiante.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\Alessander\AppData\Local\Temp\0952D34EF67DECA0378A41CAA6B9A7664B7A\4\Arquimedes\Arquimedes\Views\Estudiante\ActualizarEstudiante.cshtml"
  
    Layout = null;


#line default
#line hidden

#line 3 "C:\Users\Alessander\AppData\Local\Temp\0952D34EF67DECA0378A41CAA6B9A7664B7A\4\Arquimedes\Arquimedes\Views\Estudiante\ActualizarEstudiante.cshtml"
    using (Html.BeginForm())
    {
        

#line default
#line hidden

#line 4 "C:\Users\Alessander\AppData\Local\Temp\0952D34EF67DECA0378A41CAA6B9A7664B7A\4\Arquimedes\Arquimedes\Views\Estudiante\ActualizarEstudiante.cshtml"
   __o = Html.AntiForgeryToken();


#line default
#line hidden

#line 5 "C:\Users\Alessander\AppData\Local\Temp\0952D34EF67DECA0378A41CAA6B9A7664B7A\4\Arquimedes\Arquimedes\Views\Estudiante\ActualizarEstudiante.cshtml"
                                

        

#line default
#line hidden

#line 6 "C:\Users\Alessander\AppData\Local\Temp\0952D34EF67DECA0378A41CAA6B9A7664B7A\4\Arquimedes\Arquimedes\Views\Estudiante\ActualizarEstudiante.cshtm       __o = Html.ValidationSummary(true, "", new { @class = "text-red-600" });


#line default
#line hidden

#line 7 "C:\Users\Alessander\AppData\Local\Temp\0952D34EF67DECA0378A41CAA6B9A7664B7A\4\Arquimedes\Arquimedes\Views\Estudiante\ActualizarEstudiante.cshtm       __o = Html.HiddenFor(model => model.CodEstudiante);


#line default
#line hidden

#line 8 "C:\Users\Alessander\AppData\Local\Temp\0952D34EF67DECA0378A41CAA6B9A7664B7A\4\Arquimedes\Arquimedes\Views\Estudiante\ActualizarEstudiante.cshtm           __o = Html.LabelFor(model => model.NombreEstudiante, htmlAttributes: new { @class = "block text-gray-700 font-medium mb-2" });


#line default
#line hidden

#line 9 "C:\Users\Alessander\AppData\Local\Temp\0952D34EF67DECA0378A41CAA6B9A7664B7A\4\Arquimedes\Arquimedes\Views\Estudiante\ActualizarEstudiante.cshtm           __o = Html.EditorFor(model => model.NombreEstudiante, new { htmlAttributes = new { @class = "w-full mt-1 p-2 border border-gray-300 rounded-lg focus:ring focus:ring-blue-200" } });


#line default
#line hidden

#line 10 "C:\Users\Alessander\AppData\Local\Temp\0952D34EF67DECA0378A41CAA6B9A7664B7A\4\Arquimedes\Arquimedes\Views\Estudiante\ActualizarEstudiante.cshtm           __o = Html.ValidationMessageFor(model => model.NombreEstudiante, "", new { @class = "text-red-600" });


#line default
#line hidden

#line 11 "C:\Users\Alessander\AppData\Local\Temp\0952D34EF67DECA0378A41CAA6B9A7664B7A\4\Arquimedes\Arquimedes\Views\Estudiante\ActualizarEstudiante.cshtm           __o = Html.LabelFor(model => model.ApellidoEstudiante, htmlAttributes: new { @class = "block text-gray-700 font-medium mb-2" });


#line default
#line hidden

#line 12 "C:\Users\Alessander\AppData\Local\Temp\0952D34EF67DECA0378A41CAA6B9A7664B7A\4\Arquimedes\Arquimedes\Views\Estudiante\ActualizarEstudiante.cshtm           __o = Html.EditorFor(model => model.ApellidoEstudiante, new { htmlAttributes = new { @class = "w-full mt-1 p-2 border border-gray-300 rounded-lg focus:ring focus:ring-blue-200" } });


#line default
#line hidden

#line 13 "C:\Users\Alessander\AppData\Local\Temp\0952D34EF67DECA0378A41CAA6B9A7664B7A\4\Arquimedes\Arquimedes\Views\Estudiante\ActualizarEstudiante.cshtm           __o = Html.ValidationMessageFor(model => model.ApellidoEstudiante, "", new { @class = "text-red-600" });


#line default
#line hidden

#line 14 "C:\Users\Alessander\AppData\Local\Temp\0952D34EF67DECA0378A41CAA6B9A7664B7A\4\Arquimedes\Arquimedes\Views\Estudiante\ActualizarEstudiante.cshtm           __o = Html.LabelFor(model => model.EdadEstudiante, htmlAttributes: new { @class = "block text-gray-700 font-medium mb-2" });


#line default
#line hidden

#line 15 "C:\Users\Alessander\AppData\Local\Temp\0952D34EF67DECA0378A41CAA6B9A7664B7A\4\Arquimedes\Arquimedes\Views\Estudiante\ActualizarEstudiante.cshtm           __o = Html.EditorFor(model => model.EdadEstudiante, new { htmlAttributes = new { @class = "w-full mt-1 p-2 border border-gray-300 rounded-lg focus:ring focus:ring-blue-200" } });


#line default
#line hidden

#line 16 "C:\Users\Alessander\AppData\Local\Temp\0952D34EF67DECA0378A41CAA6B9A7664B7A\4\Arquimedes\Arquimedes\Views\Estudiante\ActualizarEstudiante.cshtm           __o = Html.ValidationMessageFor(model => model.EdadEstudiante, "", new { @class = "text-red-600" });


#line default
#line hidden

#line 17 "C:\Users\Alessander\AppData\Local\Temp\0952D34EF67DECA0378A41CAA6B9A7664B7A\4\Arquimedes\Arquimedes\Views\Estudiante\ActualizarEstudiante.cshtm       l"
    __o = Html.DropDownList("AnioEstudiante", new SelectList(new[] {
                    new { Value = "1° Grado", Text = "1° Grado" },
                    new { Value = "2° Grado", Text = "2° Grado" },
                    new { Value = "3° Grado", Text = "3° Grado" },
                    new { Value = "4° Grado", Text = "4° Grado" },
                    new { Value = "5° Grado", Text = "5° Grado" },
                    new { Value = "6° Grado", Text = "6° Grado" }
                }, "Value", "Text"), "Seleccione Año", new { @class = "w-full mt-1 p-2 border border-gray-300 rounded-lg focus:ring focus:ring-blue-200" });


#line default
#lin18hidden

#line 19 "C:\Users\Alessander\AppData\Local\Temp\0952D34EF67DECA0378A41CAA6B9A7664B7A\4\Arquimedes\Arquimedes\Views\Estudiante\ActualizarEshtml"
           __o = Html.ValidationMessageFor(model => model.AnioEstudiante, "", ne       w { @class = "text-red-600" });


#line default
#line hidden

#19ne 20 "C:\Users\Alessander\AppData\Local\Temp\0952D34EF67DECA0378A41CAA6B9A7664B7A\4\Arquimedes\Arquimedes\Views\Estudiante\ActualizarEstudiante.cshtml"
           __o = Html.Label("Sección", null, new { @class = "block text-gray-700 f       mb-2" });


#line default
#line hidden

#20ne 21 "C:\Users\Alessander\AppData\Local\Temp\0952D34EF67DECA0378A41CAA6B9A7664B7A\4\Arquimedes\Arquimedes\Views\Estudiante\ActualizarEstudiante.cshtml"
           __o = Html.DropDownList("SeccionEstudiante", new SelectList(new[] {
                new { Value = "A", Text = "A" },
                    new { Value = "B", Text = "B" },
                    new { Value = "C", Text = "C" },
                    new { Value = "D", Text = "D" }
                }, "Value", "Text"), "Seleccione Sección", new { @class = "w-full mt-1 p-2 border border-gray-300 rounded-lg focus:ring focus:ring-blue-200" });


#line default
#line hidden

#21ne 22 "C:\Users\Alessander\AppData\Local\Temp\0952D34EF67DECA0378A41CAA6B9A7664B7A\4\Arquimedes\Arquimedes\Views\Estudiante\ActualizarEstudiante.cshtml"
           __o = Html.ValidationMessageFor(model => model.Secc       te, "", new { @class = "text-red-600" });


#line default
#line hidden

#22ne 23 "C:\Users\Alessander\AppData\Local\Temp\0952D34EF67DECA0378A41CAA6B9A7664B7A\4\Arquimedes\Arquimedes\Views\Estudiante\ActualizarEstudiante.cshtml"
           __o = Html.Label("Grado Académico", null, new { @cl       k text-gray-700 font-medium mb-2" });


#line default
#line hidden

#23ne 24 "C:\Users\Alessander\AppData\Local\Temp\0952D34EF67DECA0378A41CAA6B9A7664B7A\4\Arquimedes\Arquimedes\Views\Estudiante\ActualizarEstudiante.cshtml"
           __o = Html.DropDownList("GradoAcademico", new Selec        {
                    new { Value = "Primaria", Text = "Primaria" },
                    new { Value = "Secundaria", Text = "Secundaria" }
                }, "Value", "Text"), "Seleccione Grado Académico", new { @class = "w-full mt-1 p-2 border border-gray-300 rounded-lg focus:ring focus:ring-blue-200" });


#line default
#line hidden

#24ne 25 "C:\Users\Alessander\AppData\Local\Temp\0952D34EF67DECA0378A41CAA6B9A7664B7A\4\Arquimedes\Arquimedes\Views\Estudiante\ActualizarEstudiante.cshtml"
           __o = Html.ValidationMessageFor(model =       doAcademico, "", new { @class = "text-red-600" });


#line default
#line hidden

#25ne 26 "C:\Users\Alessander\AppData\Local\Temp\0952D34EF67DECA0378A41CAA6B9A7664B7A\4\Arquimedes\Arquimedes\Views\Estudiante\ActualizarEstudiante.cshtml"
           __o = Html.LabelFor(model => model.Tele       ttributes: new { @class = "block text-gray-700 font-medium mb-2" });


#line default
#line hidden

#26ne 27 "C:\Users\Alessander\AppData\Local\Temp\0952D34EF67DECA0378A41CAA6B9A7664B7A\4\Arquimedes\Arquimedes\Views\Estudiante\ActualizarEstudiante.cshtml"
           __o = Html.EditorFor(model => model.Tel       { htmlAttributes = new { @class = "w-full mt-1 p-2 border border-gray-300 rounded-lg focus:ring focus:ring-blue-200" } });


#line default
#line hidden

#27ne 28 "C:\Users\Alessander\AppData\Local\Temp\0952D34EF67DECA0378A41CAA6B9A7664B7A\4\Arquimedes\Arquimedes\Views\Estudiante\ActualizarEstudiante.cshtml"
           __o = Html.ValidationMessageFor(model =       efono, "", new { @class = "text-red-600" });


#line default
#line hidden

#28ne 29 "C:\Users\Alessander\AppData\Local\Temp\0952D34EF67DECA0378A41CAA6B9A7664B7A\4\Arquimedes\Arquimedes\Views\Estudiante\ActualizarEstudiante.cshtml"
           __o = Html.LabelFor(model => model.Dire       Attributes: new { @class = "block text-gray-700 font-medium mb-2" });


#line default
#line hidden

#29ne 30 "C:\Users\Alessander\AppData\Local\Temp\0952D34EF67DECA0378A41CAA6B9A7664B7A\4\Arquimedes\Arquimedes\Views\Estudiante\ActualizarEstudiante.cshtml"
           __o = Html.EditorFor(model => model.Dir        { htmlAttributes = new { @class = "w-full mt-1 p-2 border border-gray-300 rounded-lg focus:ring focus:ring-blue-200" } });


#line default
#line hidden

#30ne 31 "C:\Users\Alessander\AppData\Local\Temp\0952D34EF67DECA0378A41CAA6B9A7664B7A\4\Arquimedes\Arquimedes\Views\Estudiante\ActualizarEstudiante.cshtml"
           __o = Html.ValidationMessageFor(model =       eccion, "", new { @class = "text-red-600" });


#line default
#line hidden

#31ne 32 "C:\Users\Alessander\AppData\Local\Temp\0952D34EF67DECA0378A41CAA6B9A7664B7A\4\Arquimedes\Arquimedes\Views\Estudiante\ActualizarEstudiante.cshtml"
           __o = Html.Label("Estado", null, new {        lock text-gray-700 font-medium mb-2" });


#line default
#line hidden

#32ne 33 "C:\Users\Alessander\AppData\Local\Temp\0952D34EF67DECA0378A41CAA6B9A7664B7A\4\Arquimedes\Arquimedes\Views\Estudiante\ActualizarEstudiante.cshtml"
           __o = Html.DropDownList("EstadoEstudian       lectList(new[] {
                    new { Value = "Activo", Text = "Activo" },
                    new { Value = "Inactivo", Text = "Inactivo" }
                }, "Value", "Text"), "Seleccione Estado", new { @class = "w-full mt-1 p-2 border border-gray-300 rounded-lg focus:ring focus:ring-blue-200" });


#line default
#line hidden

#33ne 34 "C:\Users\Alessander\AppData\Local\Temp\0952D34EF67DECA0378A41CAA6B9A7664B7A\4\Arquimedes\Arquimedes\Views\Estudiante\ActualizarEstudiante.cshtml"
           __o = Html.ValidationMessag       => model.EstadoEstudiante, "", new { @class = "text-red-600" });


#line default
#line hidden

#34ne 35 "C:\Users\Alessander\AppData\Local\Temp\0952D34EF67DECA0378A41CAA6B9A7664B7A\4\Arquimedes\Arquimedes\Views\Estudiante\ActualizarEstudiante.cshtml"
           __o = Html.LabelFor(model =       Estudiante, htmlAttributes: new { @class = "block text-gray-700 font-medium mb-2" });


#line default
#line hidden

#35ne 36 "C:\Users\Alessander\AppData\Local\Temp\0952D34EF67DECA0378A41CAA6B9A7664B7A\4\Arquimedes\Arquimedes\Views\Estudiante\ActualizarEstudiante.cshtml"
           __o = Html.EditorFor(model        iEstudiante, new { htmlAttributes = new { @class = "w-full mt-1 p-2 border border-gray-300 rounded-lg focus:ring focus:ring-blue-200" } });


#line default
#line hidden

#36ne 37 "C:\Users\Alessander\AppData\Local\Temp\0952D34EF67DECA0378A41CAA6B9A7664B7A\4\Arquimedes\Arquimedes\Views\Estudiante\ActualizarEstudiante.cshtml"
           __o = Html.ValidationMessag       => model.DniEstudiante, "", new { @class = "text-red-600" });


#line default
#line hidden

#37ne 38 "C:\Users\Alessander\AppData\Local\Temp\0952D34EF67DECA0378A41CAA6B9A7664B7A\4\Arquimedes\Arquimedes\Views\Estudiante\ActualizarEstudiante.cshtml"
              
    }

#line default          

#38ne 39 "C:\Users\Alessander\AppData\Local\Temp\0952D34EF67DECA0378A41CAA6B9A7664B7A\4\Arquimedes\Arquimedes\Views\Estudiante\ActualizarEstudiante.cshtml"
   __o = Html.ActionLink("Volver a la Lista", "Index", null, new { @class = "text-blue-500 hover:underline" });


#line default
#line hidden
}
}
}
